#!/bin/bash
# Build the complete NeurIPS submission package from raw evaluation data.
# Usage: ./build-paper.sh [--skip-analysis] [--skip-compile]
#
# Steps:
#   1. Activate Python venv and set working directory
#   2. Run analysis pipeline (tables, figures, stats)
#   3. Compile LaTeX with tectonic
#   4. Create submission.zip
#   5. Print summary
set -e

# ============================================================
# Parse flags
# ============================================================

SKIP_ANALYSIS=false
SKIP_COMPILE=false

for arg in "$@"; do
  case "$arg" in
    --skip-analysis) SKIP_ANALYSIS=true ;;
    --skip-compile)  SKIP_COMPILE=true ;;
    --help|-h)
      echo "Usage: ./build-paper.sh [--skip-analysis] [--skip-compile]"
      echo ""
      echo "  --skip-analysis   Skip the Python analysis pipeline (reuse existing tables/figures)"
      echo "  --skip-compile    Skip LaTeX compilation (only regenerate analysis)"
      echo ""
      exit 0
      ;;
    *)
      echo "Unknown flag: $arg"
      exit 1
      ;;
  esac
done

# ============================================================
# Resolve directories
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PAPER_DIR="$SCRIPT_DIR"
BENCHMARKS_DIR="$(cd "$PAPER_DIR/../benchmarks" && pwd)"
RESULTS_DIR="$BENCHMARKS_DIR/results"
ANALYSIS_OUTPUT_DIR="$BENCHMARKS_DIR/analysis_output"

echo "========================================"
echo "  NeurIPS Submission Build Pipeline"
echo "========================================"
echo ""
echo "Paper dir:     $PAPER_DIR"
echo "Benchmarks:    $BENCHMARKS_DIR"
echo "Results:       $RESULTS_DIR"
echo "Analysis out:  $ANALYSIS_OUTPUT_DIR"
echo ""

# ============================================================
# Step 1: Activate Python venv
# ============================================================

VENV_PATHS=(
  "$PAPER_DIR/../../.venv"        # repo-root .venv (local)
  "$HOME/deepwork/.venv"          # VPS standard path
  "$BENCHMARKS_DIR/.venv"         # benchmarks-local venv
)

VENV_FOUND=false
for vp in "${VENV_PATHS[@]}"; do
  if [ -f "$vp/bin/activate" ]; then
    echo "[1/5] Activating venv: $vp"
    source "$vp/bin/activate"
    VENV_FOUND=true
    break
  fi
done

if [ "$VENV_FOUND" = false ]; then
  echo "[1/5] WARNING: No Python venv found. Trying system Python..."
  echo "       Searched: ${VENV_PATHS[*]}"
fi

# ============================================================
# Step 2: Run analysis pipeline
# ============================================================

if [ "$SKIP_ANALYSIS" = true ]; then
  echo "[2/5] Skipping analysis (--skip-analysis)"
else
  echo "[2/5] Running analysis pipeline..."

  if [ ! -d "$RESULTS_DIR" ]; then
    echo "ERROR: Results directory not found: $RESULTS_DIR"
    exit 2
  fi

  if [ ! -f "$BENCHMARKS_DIR/analyze.py" ]; then
    echo "ERROR: analyze.py not found: $BENCHMARKS_DIR/analyze.py"
    exit 2
  fi

  cd "$BENCHMARKS_DIR"
  python3 analyze.py \
    --results-dir "$RESULTS_DIR" \
    --output-dir "$ANALYSIS_OUTPUT_DIR" \
    --n-bootstrap 10000

  echo ""
  echo "       Analysis complete. Output in $ANALYSIS_OUTPUT_DIR"

  # Ensure stats.tex exists (the paper \input's it)
  STATS_FILE="$ANALYSIS_OUTPUT_DIR/stats.tex"
  if [ ! -f "$STATS_FILE" ]; then
    echo "       Note: stats.tex not generated by pipeline, creating empty stub"
    mkdir -p "$ANALYSIS_OUTPUT_DIR"
    echo "% Auto-generated stats placeholder — analysis pipeline did not produce stats.tex" > "$STATS_FILE"
  fi
fi

# ============================================================
# Step 3: Compile LaTeX
# ============================================================

if [ "$SKIP_COMPILE" = true ]; then
  echo "[3/5] Skipping LaTeX compilation (--skip-compile)"
else
  echo "[3/5] Compiling LaTeX with tectonic..."

  cd "$PAPER_DIR"

  # Ensure stats.tex exists before compilation (paper \input's it)
  STATS_FILE="$ANALYSIS_OUTPUT_DIR/stats.tex"
  if [ ! -f "$STATS_FILE" ]; then
    echo "       Creating empty stats.tex stub for compilation"
    mkdir -p "$ANALYSIS_OUTPUT_DIR"
    echo "% Auto-generated stats placeholder" > "$STATS_FILE"
  fi

  tectonic main.tex
  echo "       Compilation successful."
fi

# ============================================================
# Step 4: Create submission package
# ============================================================

echo "[4/5] Creating submission package..."

cd "$PAPER_DIR"

SUBMISSION_ZIP="$PAPER_DIR/submission.zip"

# Remove old zip if present
rm -f "$SUBMISSION_ZIP"

# Build the zip from the paper directory
ZIP_FILES=()

# main.pdf
if [ -f "main.pdf" ]; then
  ZIP_FILES+=("main.pdf")
else
  echo "WARNING: main.pdf not found — was compilation skipped?"
fi

# main.tex
ZIP_FILES+=("main.tex")

# Style file
if [ -f "neurips_2026.sty" ]; then
  ZIP_FILES+=("neurips_2026.sty")
fi

# Bibliography
if [ -f "main.bbl" ]; then
  ZIP_FILES+=("main.bbl")
fi

# Create zip with paper files
if [ ${#ZIP_FILES[@]} -gt 0 ]; then
  zip -q "$SUBMISSION_ZIP" "${ZIP_FILES[@]}"
fi

# Add analysis_output directory (relative path from paper dir)
if [ -d "$ANALYSIS_OUTPUT_DIR" ]; then
  cd "$PAPER_DIR/.."
  zip -qr "$SUBMISSION_ZIP" "benchmarks/analysis_output/"
  cd "$PAPER_DIR"
else
  echo "WARNING: analysis_output directory not found — was analysis skipped?"
fi

echo "       Created: $SUBMISSION_ZIP"

# ============================================================
# Step 5: Summary
# ============================================================

echo ""
echo "[5/5] Build Summary"
echo "========================================"

if [ -f "main.pdf" ]; then
  # Page count (use pdfinfo if available, otherwise estimate)
  if command -v pdfinfo &> /dev/null; then
    PAGES=$(pdfinfo main.pdf 2>/dev/null | grep "Pages:" | awk '{print $2}')
    echo "  Pages:     $PAGES"
  fi
  PDF_SIZE=$(ls -lh main.pdf | awk '{print $5}')
  echo "  PDF size:  $PDF_SIZE"
fi

if [ -f "$SUBMISSION_ZIP" ]; then
  ZIP_SIZE=$(ls -lh "$SUBMISSION_ZIP" | awk '{print $5}')
  echo "  ZIP size:  $ZIP_SIZE"
fi

echo "  Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
echo ""
echo "  Output files:"
[ -f "main.pdf" ] && echo "    - main.pdf"
[ -f "$SUBMISSION_ZIP" ] && echo "    - submission.zip"
echo ""
echo "Done."
